export const TIME_SERIES_FETCH_SERIES_BEGIN = 'TIME_SERIES_FETCH_SERIES_BEGIN';
export const TIME_SERIES_FETCH_SERIES_SUCCESS = 'TIME_SERIES_FETCH_SERIES_SUCCESS';
export const TIME_SERIES_FETCH_SERIES_FAILURE = 'TIME_SERIES_FETCH_SERIES_FAILURE';
export const TIME_SERIES_FETCH_SERIES_DISMISS_ERROR = 'TIME_SERIES_FETCH_SERIES_DISMISS_ERROR';
